/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExerciseCreateNestedManyWithoutTrainingPlansInput } from "./ExerciseCreateNestedManyWithoutTrainingPlansInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { GoalCreateNestedManyWithoutTrainingPlansInput } from "./GoalCreateNestedManyWithoutTrainingPlansInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { WorkoutCreateNestedManyWithoutTrainingPlansInput } from "./WorkoutCreateNestedManyWithoutTrainingPlansInput";
@InputType()
class TrainingPlanCreateInput {
  @ApiProperty({
    required: false,
    type: () => ExerciseCreateNestedManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => ExerciseCreateNestedManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => ExerciseCreateNestedManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  exercise?: ExerciseCreateNestedManyWithoutTrainingPlansInput;

  @ApiProperty({
    required: false,
    type: () => GoalCreateNestedManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => GoalCreateNestedManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => GoalCreateNestedManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  goal?: GoalCreateNestedManyWithoutTrainingPlansInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  targetBodyPart?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutCreateNestedManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => WorkoutCreateNestedManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => WorkoutCreateNestedManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  workouts?: WorkoutCreateNestedManyWithoutTrainingPlansInput;
}
export { TrainingPlanCreateInput };
