/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExerciseUpdateManyWithoutTrainingPlansInput } from "./ExerciseUpdateManyWithoutTrainingPlansInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { GoalUpdateManyWithoutTrainingPlansInput } from "./GoalUpdateManyWithoutTrainingPlansInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { WorkoutUpdateManyWithoutTrainingPlansInput } from "./WorkoutUpdateManyWithoutTrainingPlansInput";
@InputType()
class TrainingPlanUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ExerciseUpdateManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => ExerciseUpdateManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => ExerciseUpdateManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  exercise?: ExerciseUpdateManyWithoutTrainingPlansInput;

  @ApiProperty({
    required: false,
    type: () => GoalUpdateManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => GoalUpdateManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => GoalUpdateManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  goal?: GoalUpdateManyWithoutTrainingPlansInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  targetBodyPart?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutUpdateManyWithoutTrainingPlansInput,
  })
  @ValidateNested()
  @Type(() => WorkoutUpdateManyWithoutTrainingPlansInput)
  @IsOptional()
  @Field(() => WorkoutUpdateManyWithoutTrainingPlansInput, {
    nullable: true,
  })
  workouts?: WorkoutUpdateManyWithoutTrainingPlansInput;
}
export { TrainingPlanUpdateInput };
