/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkoutService } from "../workout.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkoutCreateInput } from "./WorkoutCreateInput";
import { WorkoutWhereInput } from "./WorkoutWhereInput";
import { WorkoutWhereUniqueInput } from "./WorkoutWhereUniqueInput";
import { WorkoutFindManyArgs } from "./WorkoutFindManyArgs";
import { WorkoutUpdateInput } from "./WorkoutUpdateInput";
import { Workout } from "./Workout";
import { ExerciseLogFindManyArgs } from "../../exerciseLog/base/ExerciseLogFindManyArgs";
import { ExerciseLog } from "../../exerciseLog/base/ExerciseLog";
import { ExerciseLogWhereUniqueInput } from "../../exerciseLog/base/ExerciseLogWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WorkoutControllerBase {
  constructor(
    protected readonly service: WorkoutService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Workout })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: WorkoutCreateInput): Promise<Workout> {
    return await this.service.create({
      data: {
        ...data,

        exerciseLog: data.exerciseLog
          ? {
              connect: data.exerciseLog,
            }
          : undefined,

        trainingPlan: data.trainingPlan
          ? {
              connect: data.trainingPlan,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,

        exerciseLog: {
          select: {
            id: true,
          },
        },

        id: true,

        trainingPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Workout] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(WorkoutFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Workout[]> {
    const args = plainToClass(WorkoutFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        date: true,

        exerciseLog: {
          select: {
            id: true,
          },
        },

        id: true,

        trainingPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Workout })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: WorkoutWhereUniqueInput
  ): Promise<Workout | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        date: true,

        exerciseLog: {
          select: {
            id: true,
          },
        },

        id: true,

        trainingPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Workout })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: WorkoutWhereUniqueInput,
    @common.Body() data: WorkoutUpdateInput
  ): Promise<Workout | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          exerciseLog: data.exerciseLog
            ? {
                connect: data.exerciseLog,
              }
            : undefined,

          trainingPlan: data.trainingPlan
            ? {
                connect: data.trainingPlan,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,

          exerciseLog: {
            select: {
              id: true,
            },
          },

          id: true,

          trainingPlan: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Workout })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: WorkoutWhereUniqueInput
  ): Promise<Workout | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          date: true,

          exerciseLog: {
            select: {
              id: true,
            },
          },

          id: true,

          trainingPlan: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/exerciseLogs")
  @ApiNestedQuery(ExerciseLogFindManyArgs)
  async findManyExerciseLogs(
    @common.Req() request: Request,
    @common.Param() params: WorkoutWhereUniqueInput
  ): Promise<ExerciseLog[]> {
    const query = plainToClass(ExerciseLogFindManyArgs, request.query);
    const results = await this.service.findExerciseLogs(params.id, {
      ...query,
      select: {
        createdAt: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        reps: true,
        sets: true,
        updatedAt: true,
        weight: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/exerciseLogs")
  async connectExerciseLogs(
    @common.Param() params: WorkoutWhereUniqueInput,
    @common.Body() body: ExerciseLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exerciseLogs: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/exerciseLogs")
  async updateExerciseLogs(
    @common.Param() params: WorkoutWhereUniqueInput,
    @common.Body() body: ExerciseLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exerciseLogs: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/exerciseLogs")
  async disconnectExerciseLogs(
    @common.Param() params: WorkoutWhereUniqueInput,
    @common.Body() body: ExerciseLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exerciseLogs: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
