/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { ExerciseLogWhereUniqueInput } from "../../exerciseLog/base/ExerciseLogWhereUniqueInput";
import { ExerciseLogUpdateManyWithoutWorkoutsInput } from "./ExerciseLogUpdateManyWithoutWorkoutsInput";
import { TrainingPlanWhereUniqueInput } from "../../trainingPlan/base/TrainingPlanWhereUniqueInput";
@InputType()
class WorkoutUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ExerciseLogWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExerciseLogWhereUniqueInput)
  @IsOptional()
  @Field(() => ExerciseLogWhereUniqueInput, {
    nullable: true,
  })
  exerciseLog?: ExerciseLogWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ExerciseLogUpdateManyWithoutWorkoutsInput,
  })
  @ValidateNested()
  @Type(() => ExerciseLogUpdateManyWithoutWorkoutsInput)
  @IsOptional()
  @Field(() => ExerciseLogUpdateManyWithoutWorkoutsInput, {
    nullable: true,
  })
  exerciseLogs?: ExerciseLogUpdateManyWithoutWorkoutsInput;

  @ApiProperty({
    required: false,
    type: () => TrainingPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TrainingPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => TrainingPlanWhereUniqueInput, {
    nullable: true,
  })
  trainingPlan?: TrainingPlanWhereUniqueInput | null;
}
export { WorkoutUpdateInput };
