/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  IsInt,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { Exercise } from "../../exercise/base/Exercise";
import { Workout } from "../../workout/base/Workout";
@ObjectType()
class ExerciseLog {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Exercise,
  })
  @ValidateNested()
  @Type(() => Exercise)
  @IsOptional()
  exercise?: Exercise | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  reps!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sets!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  weight!: number | null;

  @ApiProperty({
    required: false,
    type: () => Workout,
  })
  @ValidateNested()
  @Type(() => Workout)
  @IsOptional()
  workout?: Workout | null;

  @ApiProperty({
    required: false,
    type: () => [Workout],
  })
  @ValidateNested()
  @Type(() => Workout)
  @IsOptional()
  workouts?: Array<Workout>;
}
export { ExerciseLog };
