/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExerciseWhereUniqueInput } from "../../exercise/base/ExerciseWhereUniqueInput";
import { ValidateNested, IsOptional, IsInt, IsNumber } from "class-validator";
import { Type } from "class-transformer";
import { WorkoutWhereUniqueInput } from "../../workout/base/WorkoutWhereUniqueInput";
import { WorkoutCreateNestedManyWithoutExerciseLogsInput } from "./WorkoutCreateNestedManyWithoutExerciseLogsInput";
@InputType()
class ExerciseLogCreateInput {
  @ApiProperty({
    required: false,
    type: () => ExerciseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExerciseWhereUniqueInput)
  @IsOptional()
  @Field(() => ExerciseWhereUniqueInput, {
    nullable: true,
  })
  exercise?: ExerciseWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  reps?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sets?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  weight?: number | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkoutWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkoutWhereUniqueInput, {
    nullable: true,
  })
  workout?: WorkoutWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutCreateNestedManyWithoutExerciseLogsInput,
  })
  @ValidateNested()
  @Type(() => WorkoutCreateNestedManyWithoutExerciseLogsInput)
  @IsOptional()
  @Field(() => WorkoutCreateNestedManyWithoutExerciseLogsInput, {
    nullable: true,
  })
  workouts?: WorkoutCreateNestedManyWithoutExerciseLogsInput;
}
export { ExerciseLogCreateInput };
