/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExerciseLogService } from "../exerciseLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExerciseLogCreateInput } from "./ExerciseLogCreateInput";
import { ExerciseLogWhereInput } from "./ExerciseLogWhereInput";
import { ExerciseLogWhereUniqueInput } from "./ExerciseLogWhereUniqueInput";
import { ExerciseLogFindManyArgs } from "./ExerciseLogFindManyArgs";
import { ExerciseLogUpdateInput } from "./ExerciseLogUpdateInput";
import { ExerciseLog } from "./ExerciseLog";
import { WorkoutFindManyArgs } from "../../workout/base/WorkoutFindManyArgs";
import { Workout } from "../../workout/base/Workout";
import { WorkoutWhereUniqueInput } from "../../workout/base/WorkoutWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExerciseLogControllerBase {
  constructor(
    protected readonly service: ExerciseLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExerciseLog })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ExerciseLogCreateInput
  ): Promise<ExerciseLog> {
    return await this.service.create({
      data: {
        ...data,

        exercise: data.exercise
          ? {
              connect: data.exercise,
            }
          : undefined,

        workout: data.workout
          ? {
              connect: data.workout,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        reps: true,
        sets: true,
        updatedAt: true,
        weight: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExerciseLog] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ExerciseLogFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ExerciseLog[]> {
    const args = plainToClass(ExerciseLogFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        reps: true,
        sets: true,
        updatedAt: true,
        weight: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExerciseLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ExerciseLogWhereUniqueInput
  ): Promise<ExerciseLog | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        reps: true,
        sets: true,
        updatedAt: true,
        weight: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExerciseLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ExerciseLogWhereUniqueInput,
    @common.Body() data: ExerciseLogUpdateInput
  ): Promise<ExerciseLog | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          exercise: data.exercise
            ? {
                connect: data.exercise,
              }
            : undefined,

          workout: data.workout
            ? {
                connect: data.workout,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          exercise: {
            select: {
              id: true,
            },
          },

          id: true,
          reps: true,
          sets: true,
          updatedAt: true,
          weight: true,

          workout: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExerciseLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ExerciseLogWhereUniqueInput
  ): Promise<ExerciseLog | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          exercise: {
            select: {
              id: true,
            },
          },

          id: true,
          reps: true,
          sets: true,
          updatedAt: true,
          weight: true,

          workout: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/workouts")
  @ApiNestedQuery(WorkoutFindManyArgs)
  async findManyWorkouts(
    @common.Req() request: Request,
    @common.Param() params: ExerciseLogWhereUniqueInput
  ): Promise<Workout[]> {
    const query = plainToClass(WorkoutFindManyArgs, request.query);
    const results = await this.service.findWorkouts(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,

        exerciseLog: {
          select: {
            id: true,
          },
        },

        id: true,

        trainingPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/workouts")
  async connectWorkouts(
    @common.Param() params: ExerciseLogWhereUniqueInput,
    @common.Body() body: WorkoutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workouts: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/workouts")
  async updateWorkouts(
    @common.Param() params: ExerciseLogWhereUniqueInput,
    @common.Body() body: WorkoutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workouts: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ExerciseLog",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/workouts")
  async disconnectWorkouts(
    @common.Param() params: ExerciseLogWhereUniqueInput,
    @common.Body() body: WorkoutWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      workouts: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
