/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsString, IsOptional, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { Difficulty } from "../../difficulty/base/Difficulty";
import { ExerciseLog } from "../../exerciseLog/base/ExerciseLog";
import { Goal } from "../../goal/base/Goal";
import { TrainingPlan } from "../../trainingPlan/base/TrainingPlan";
@ObjectType()
class Exercise {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: () => Difficulty,
  })
  @ValidateNested()
  @Type(() => Difficulty)
  @IsOptional()
  difficulty?: Difficulty | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  equipmentNeeded!: string;

  @ApiProperty({
    required: false,
    type: () => [ExerciseLog],
  })
  @ValidateNested()
  @Type(() => ExerciseLog)
  @IsOptional()
  exerciseLogs?: Array<ExerciseLog>;

  @ApiProperty({
    required: false,
    type: () => [Goal],
  })
  @ValidateNested()
  @Type(() => Goal)
  @IsOptional()
  goals?: Array<Goal>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  imageLink!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  targetbodyPart!: string | null;

  @ApiProperty({
    required: false,
    type: () => [TrainingPlan],
  })
  @ValidateNested()
  @Type(() => TrainingPlan)
  @IsOptional()
  trainingPlans?: Array<TrainingPlan>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  videoLink!: string;
}
export { Exercise };
