/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DifficultyWhereUniqueInput } from "../../difficulty/base/DifficultyWhereUniqueInput";
import { Type } from "class-transformer";
import { ExerciseLogCreateNestedManyWithoutExercisesInput } from "./ExerciseLogCreateNestedManyWithoutExercisesInput";
import { GoalCreateNestedManyWithoutExercisesInput } from "./GoalCreateNestedManyWithoutExercisesInput";
import { TrainingPlanCreateNestedManyWithoutExercisesInput } from "./TrainingPlanCreateNestedManyWithoutExercisesInput";
@InputType()
class ExerciseCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => DifficultyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DifficultyWhereUniqueInput)
  @IsOptional()
  @Field(() => DifficultyWhereUniqueInput, {
    nullable: true,
  })
  difficulty?: DifficultyWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  equipmentNeeded!: string;

  @ApiProperty({
    required: false,
    type: () => ExerciseLogCreateNestedManyWithoutExercisesInput,
  })
  @ValidateNested()
  @Type(() => ExerciseLogCreateNestedManyWithoutExercisesInput)
  @IsOptional()
  @Field(() => ExerciseLogCreateNestedManyWithoutExercisesInput, {
    nullable: true,
  })
  exerciseLogs?: ExerciseLogCreateNestedManyWithoutExercisesInput;

  @ApiProperty({
    required: false,
    type: () => GoalCreateNestedManyWithoutExercisesInput,
  })
  @ValidateNested()
  @Type(() => GoalCreateNestedManyWithoutExercisesInput)
  @IsOptional()
  @Field(() => GoalCreateNestedManyWithoutExercisesInput, {
    nullable: true,
  })
  goals?: GoalCreateNestedManyWithoutExercisesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  imageLink!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  targetbodyPart?: string | null;

  @ApiProperty({
    required: false,
    type: () => TrainingPlanCreateNestedManyWithoutExercisesInput,
  })
  @ValidateNested()
  @Type(() => TrainingPlanCreateNestedManyWithoutExercisesInput)
  @IsOptional()
  @Field(() => TrainingPlanCreateNestedManyWithoutExercisesInput, {
    nullable: true,
  })
  trainingPlans?: TrainingPlanCreateNestedManyWithoutExercisesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  videoLink!: string;
}
export { ExerciseCreateInput };
