/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GoalService } from "../goal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoalCreateInput } from "./GoalCreateInput";
import { GoalWhereInput } from "./GoalWhereInput";
import { GoalWhereUniqueInput } from "./GoalWhereUniqueInput";
import { GoalFindManyArgs } from "./GoalFindManyArgs";
import { GoalUpdateInput } from "./GoalUpdateInput";
import { Goal } from "./Goal";
import { TrainingPlanFindManyArgs } from "../../trainingPlan/base/TrainingPlanFindManyArgs";
import { TrainingPlan } from "../../trainingPlan/base/TrainingPlan";
import { TrainingPlanWhereUniqueInput } from "../../trainingPlan/base/TrainingPlanWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GoalControllerBase {
  constructor(
    protected readonly service: GoalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Goal })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: GoalCreateInput): Promise<Goal> {
    return await this.service.create({
      data: {
        ...data,

        exercise: data.exercise
          ? {
              connect: data.exercise,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        currentReps: true,
        currentWeight: true,
        deadline: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        motivation: true,
        targetReps: true,
        targetWeight: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Goal] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(GoalFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Goal[]> {
    const args = plainToClass(GoalFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        currentReps: true,
        currentWeight: true,
        deadline: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        motivation: true,
        targetReps: true,
        targetWeight: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Goal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: GoalWhereUniqueInput
  ): Promise<Goal | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        currentReps: true,
        currentWeight: true,
        deadline: true,

        exercise: {
          select: {
            id: true,
          },
        },

        id: true,
        motivation: true,
        targetReps: true,
        targetWeight: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Goal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: GoalWhereUniqueInput,
    @common.Body() data: GoalUpdateInput
  ): Promise<Goal | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          exercise: data.exercise
            ? {
                connect: data.exercise,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          currentReps: true,
          currentWeight: true,
          deadline: true,

          exercise: {
            select: {
              id: true,
            },
          },

          id: true,
          motivation: true,
          targetReps: true,
          targetWeight: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Goal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: GoalWhereUniqueInput
  ): Promise<Goal | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          currentReps: true,
          currentWeight: true,
          deadline: true,

          exercise: {
            select: {
              id: true,
            },
          },

          id: true,
          motivation: true,
          targetReps: true,
          targetWeight: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TrainingPlan",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/trainingPlans")
  @ApiNestedQuery(TrainingPlanFindManyArgs)
  async findManyTrainingPlans(
    @common.Req() request: Request,
    @common.Param() params: GoalWhereUniqueInput
  ): Promise<TrainingPlan[]> {
    const query = plainToClass(TrainingPlanFindManyArgs, request.query);
    const results = await this.service.findTrainingPlans(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        targetBodyPart: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/trainingPlans")
  async connectTrainingPlans(
    @common.Param() params: GoalWhereUniqueInput,
    @common.Body() body: TrainingPlanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingPlans: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/trainingPlans")
  async updateTrainingPlans(
    @common.Param() params: GoalWhereUniqueInput,
    @common.Body() body: TrainingPlanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingPlans: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Goal",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/trainingPlans")
  async disconnectTrainingPlans(
    @common.Param() params: GoalWhereUniqueInput,
    @common.Body() body: TrainingPlanWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainingPlans: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
