/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DifficultyService } from "../difficulty.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DifficultyCreateInput } from "./DifficultyCreateInput";
import { DifficultyWhereInput } from "./DifficultyWhereInput";
import { DifficultyWhereUniqueInput } from "./DifficultyWhereUniqueInput";
import { DifficultyFindManyArgs } from "./DifficultyFindManyArgs";
import { DifficultyUpdateInput } from "./DifficultyUpdateInput";
import { Difficulty } from "./Difficulty";
import { ExerciseFindManyArgs } from "../../exercise/base/ExerciseFindManyArgs";
import { Exercise } from "../../exercise/base/Exercise";
import { ExerciseWhereUniqueInput } from "../../exercise/base/ExerciseWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DifficultyControllerBase {
  constructor(
    protected readonly service: DifficultyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Difficulty })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: DifficultyCreateInput
  ): Promise<Difficulty> {
    return await this.service.create({
      data: data,
      select: {
        advanced: true,
        beginner: true,
        createdAt: true,
        elite: true,
        expert: true,
        id: true,
        intermediate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Difficulty] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DifficultyFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Difficulty[]> {
    const args = plainToClass(DifficultyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        advanced: true,
        beginner: true,
        createdAt: true,
        elite: true,
        expert: true,
        id: true,
        intermediate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Difficulty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DifficultyWhereUniqueInput
  ): Promise<Difficulty | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        advanced: true,
        beginner: true,
        createdAt: true,
        elite: true,
        expert: true,
        id: true,
        intermediate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Difficulty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DifficultyWhereUniqueInput,
    @common.Body() data: DifficultyUpdateInput
  ): Promise<Difficulty | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          advanced: true,
          beginner: true,
          createdAt: true,
          elite: true,
          expert: true,
          id: true,
          intermediate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Difficulty })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DifficultyWhereUniqueInput
  ): Promise<Difficulty | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          advanced: true,
          beginner: true,
          createdAt: true,
          elite: true,
          expert: true,
          id: true,
          intermediate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/exercises")
  @ApiNestedQuery(ExerciseFindManyArgs)
  async findManyExercises(
    @common.Req() request: Request,
    @common.Param() params: DifficultyWhereUniqueInput
  ): Promise<Exercise[]> {
    const query = plainToClass(ExerciseFindManyArgs, request.query);
    const results = await this.service.findExercises(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,

        difficulty: {
          select: {
            id: true,
          },
        },

        equipmentNeeded: true,
        id: true,
        imageLink: true,
        name: true,
        targetbodyPart: true,
        updatedAt: true,
        videoLink: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/exercises")
  async connectExercises(
    @common.Param() params: DifficultyWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/exercises")
  async updateExercises(
    @common.Param() params: DifficultyWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Difficulty",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/exercises")
  async disconnectExercises(
    @common.Param() params: DifficultyWhereUniqueInput,
    @common.Body() body: ExerciseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exercises: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
